export const config = {
    CHAT_PROJECT_ID: process.env.REACT_APP_CHAT_PROJECT_ID,
    CHAT_PRIVATE_KEY: process.env.REACT_APP_CHAT_PRIVATE_KEY,
    CHAT_ADMIN_USERNAME: process.env.REACT_APP_CHAT_ADMIN_USERNAME,
    CHAT_ADMIN_SECRET: process.env.REACT_APP_CHAT_ADMIN_SECRET
}